services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  TYPO3\CMS\Seo\:
    resource: '../Classes/*'

  TYPO3\CMS\Seo\HrefLang\HrefLangGenerator:
    tags:
      - name: event.listener
        identifier: 'typo3-seo/hreflangGenerator'

  TYPO3\CMS\Seo\MetaTag\MetaTagGenerator:
    public: true

  TYPO3\CMS\Seo\XmlSitemap\XmlSitemapRenderer:
    public: true

  TYPO3\CMS\Seo\Widgets\Provider\PagesWithoutDescriptionDataProvider:
    arguments:
      $excludedDoktypes: [ 3, 4, 6, 7, 199, 254, 255 ]
      $limit: 8

  dashboard.widget.pagesWithoutMetaDescription:
    class: TYPO3\CMS\Seo\Widgets\PagesWithoutDescriptionWidget
    arguments:
      $dataProvider: '@TYPO3\CMS\Seo\Widgets\Provider\PagesWithoutDescriptionDataProvider'
      $options:
        refreshAvailable: true
    tags:
      - name: dashboard.widget
        identifier: 'seo-pagesWithoutMetaDescription'
        groupNames: 'seo'
        title: 'LLL:EXT:seo/Resources/Private/Language/locallang_dashboard.xlf:widget.pagesWithoutMetaDescription.title'
        description: 'LLL:EXT:seo/Resources/Private/Language/locallang_dashboard.xlf:widget.pagesWithoutMetaDescription.description'
        iconIdentifier: 'content-widget-list'
        height: 'large'
        width: 'medium'
