settings:
  seo.sitemap.view.templateRootPath:
    default: 'EXT:seo/Resources/Private/Templates/'
    type: string
  seo.sitemap.view.partialRootPath:
    default: 'EXT:seo/Resources/Private/Partials/'
    type: string
  seo.sitemap.view.layoutRootPath:
    default: 'EXT:seo/Resources/Private/Layouts/'
    type: string
  seo.sitemap.pages.excludedDoktypes:
    default: '3, 4, 6, 7, 199, 254'
    type: string
  seo.sitemap.pages.excludePagesRecursive:
    default: ''
    type: string
  seo.sitemap.pages.additionalWhere:
    default: "{#no_index} = 0 AND {#canonical_link} = ''"
    type: string
